config/routes.rb
ShoYu::Application.routes.draw do
  
  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => "confirmations",
    omniauth_callbacks: 'omniauth_callbacks'
  }
  
  root to:"static_pages#home"
  
  resources :users, only: [:show, :index] do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :contacts, only: [:new, :create]
  match '/about', to: 'static_pages#about', via: 'get'
  match '/link', to: 'static_pages#link', via: 'get'
  match '/search', to: 'users#search' , via: 'get'
  match '/comfirm', to: 'static_pages#comfirm', via:'get'
  match '/sending', to: 'static_pages#sending', via:'get'
  match '/sending_contact', to: 'static_pages#sending_contact', via:'get'
  
  match '/message', to: 'messages#index' , via:'get'
  post 'post' => 'messages#post'
  post "messages/read_session"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  
  #association
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  #peperclip
  has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png image/gif)
  
  #validates
  validates :name, presence: true, length:  { maximum: 30 }
  validates :name, uniqueness: true
  validates :password, length:  { minimum: 8 }, on: [:new] 
  validate :sex_check
  validate :birthday_check
  validate :area_check
  validate :password_confirmation_check, on: [:new]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
         
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    
    unless user
    
      birthday = self.birthdayEditer(auth.extra.raw_info.birthday)
      age = self.ageEditer(birthday)
      sex = self.sexEditer(auth.extra.raw_info.gender)
      location = locationEditer(auth.info.location)
      imageUrl = auth.info.image + "?type=large"
      require 'open-uri'
      require 'open_uri_redirections'
      image = open(imageUrl, :allow_redirections => :safe)
    
      user = User.new(
          uid: auth.uid,
          provider: auth.provider,
          name: auth.info.name,
          email: auth.info.email,
          image: image,
          birthday: birthday,
          age: age,
          sex: sex,
          area: location,
          password: Devise.friendly_token[10, 15],
          confirmed_at: Time.now)
      user.save
    end

    user
    
  end
  
  def update_without_current_password(params, *options)
    params.delete(:current_password)
 
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
 
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
  
  # relationship utility
  
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end
  
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
  
  # original varidate method 
  def sex_check
    if sex.blank?
        errors.add(:sex, "を入力してください")
    end  
  end
  
  def birthday_check
    if birthday.empty?
        errors.add(:birthday, "を入力してください")
      else if ! birthday =~ /\dD{4}\/\dD{2}\/\dD{2}/
        errors.add(:birthday, "の書式が正しくありません \n/は自動で入力されます")
      else
        birthdayArr = Array.new
        birthdayArr = birthday.split('/')
        year = birthdayArr[0].to_i
        month = birthdayArr[1].to_i
        day = birthdayArr[2].to_i
        unless Date.valid_date?(year,month,day)
          errors.add(:birthday, "に存在しない日付が入力されています")
        end
      end
    end
  end
    
  def area_check
    if area.empty?
        errors.add(:area, "を入力してください")
    end
  end
  
  def kiryoku_check
    if kiryoku.empty?
        errors.add(:kiryoku, "を入力してください")
    end 
  end
  
  def password_confirmation_check
    if password.present?
      if password_confirmation.empty?
        errors.add(:password_confirmation, "を入力してください")
      end
    end
  end
  
  #faceBook data edit
  def self.sexEditer(sex)
    if sex == "male"
      return 1
    else
      return 2
    end
  end
  
  def self.birthdayEditer(birthday)
    year = birthday[6,4]
    month = birthday[0,2]
    day = birthday[3,2]
    userBirthday = year + "/" + month + "/" + day
    return userBirthday
  end
  
  def self.ageEditer(userBirthday)
    birthday = Date.strptime(userBirthday,'%Y/%m/%d')
    birthdayInt = birthday.strftime("%Y%m%d").to_i
    todayInt = Date.today.strftime("%Y%m%d").to_i
    return (todayInt - birthdayInt) / 10000
  end
  
  def self.locationEditer(location)
    userLocationArr = location.split(',')
    userPrefectures = userLocationArr[1].strip
    pref = JpPrefecture::Prefecture.find name: userPrefectures
    return pref.name
  end

  def self.searchUser(area,kiryoku,age,myid)

    if area.blank? && kiryoku.blank? && age.blank?
      return User.all.where.not(id: myid)
    end
    
    serach_keys = Array.new
    serach_values = Array.new

    if area.present?
      serach_keys.push('area')
      serach_values.push(area)
    end
    
    if kiryoku.present?
      serach_keys.push('kiryoku')
      serach_values.push(kiryoku)
    end
    
    if age.present?
      ageArr = ["10代前半","10代後半","20代前半","20代後半","30代前半","30代後半","40代前半","40代後半","50代前半","50代後半","60歳以上"]
      rangeArr = [10..14 , 15..19, 20..24, 25..29, 30..34, 35..39, 40..44, 45..49, 50..54, 55..59, 60..150]
      
      for index in 0..ageArr.length - 1 do
        if age == ageArr[index]
          ageRange = rangeArr[index]
        end
      end
      
      serach_keys.push('age')
      serach_values.push(ageRange)
    end
    
    users = User.getUser(serach_keys,serach_values,myid)
    users
    
  end
  
  def self.getUser (search_keys, search_values, myid)
    conditions = nil
    search_keys.each_with_index do |search_key, i|
      if conditions.present?
        
        if(search_key == "age") 
          conditions = conditions.and(arel_table[search_key].in(search_values[i]))
        else 
          conditions = conditions.and(arel_table[search_key].eq(search_values[i]))
        end
        
      else
        if(search_key == "age") 
          conditions = arel_table[search_key].in(search_values[i])
        else
          conditions = arel_table[search_key].eq(search_values[i])
        end
        
      end 
    end
    
    conditions = conditions.and(arel_table["id"].not_eq(myid))
    where(conditions)
  end
  
  def self.getPartnerInf(partner_id)
      partner_inf = User.find(partner_id)
      partner_inf
  end
  
  def self.checkFriend(friends, partner_id)
      if friends.where(uid: partner_id).nil?
        friend_flag = false
      else
        friend_flag = true
      end
      friend_flag
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def index
    @users = User.searchUser(params[:user]["area"], params[:user]["kiryoku"], params[:user]["age"], params[:user]["id"])
    @users = @users.paginate(:page => params[:page], :per_page => 8)
  end
  
  def search
    @user = User.new
  end
  
  def following
    @title = "友達登録しているユーザ"
    @user = User.find(params[:id])
    @users = @user.followed_users
    @users = @users.paginate(:page => params[:page], :per_page => 8)
    render 'show_follow'
  end
  
  def followers
    @title = "友達登録されているユーザ"
    @user = User.find(params[:id])
    @users = @user.followers
    @users = @users.paginate(:page => params[:page], :per_page => 8)
    render 'show_follow'
  end
  
  private
  
    def user_params
      params.require(:user).permit(:content, :image)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
    
    def gravatar_for(user,options = { size: 50} )
        gravatar_id = gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
    
end

app/views/users/index.html.erb
<% content_for :index do %>
	<%= stylesheet_link_tag "layout/main" %>
	<%= stylesheet_link_tag "container/index" %>
<% end %>

<div class="main-section-head mdl-typography--display-1">
	<div class="main-section-head__title">
		検索結果        
	</div>
	<div class="main-section-head__button">    
		<%= link_to "検索条件を変更する", search_path, 
		{ :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect 
		mdl-button--accent mdl-color--teal-300" } %>
	</div>
</div>

<div class="index-card-container mdl-grid">
	<% if @users.count == 0 %>
		<h4>検索条件に一致するユーザーが見つかりませんでした</h4>
	<% end %>
	
	<% @users.each do |user| %>
		<div class="mdl-card mdl-shadow--4dp mdl-cell mdl-cell--3-col mdl-color--lime-50">
			<div class="mdl-card__media">
				<% if ! user.image_file_name.nil? %>
					<%= image_tag user.image.url , :size => "200x200" %>
				<% else %>
					<%= image_tag "link/noImage.png" , :size => "200x200" %>
				<% end %>
			</div>
			<div class="mdl-card__title">
				<h4 class="mdl-card__title-text"><%= user.name %></h4>
			</div>
			<div class="mdl-card__supporting-text">
				<span class="mdl-typography--font-light mdl-typography--subhead">
					<ul style="list-style:none">
						<li>性別: <% if user.sex == 1 %> 男性 <% else %> 女性 <% end %></li>
  		  		    	<li>棋力: <%= user.kiryoku %></li>
  		  		    	<li>地域: <%= user.area %></li>
  		  		    	<li>年齢: <%= user.age %></li>
  		  		    </ul>
  		  		</span>
  		  	</div>
			<div class="mdl-card__actions">
				<%= link_to user, { :class => "multiple-link mdl-button mdl-js-button mdl-typography--text-uppercase" }  do %>
					<span class="icon-link">プロフィールを開く
						<i class="material-icons">chevron_right</i>
					</span>
				<% end %>
			</div>
		</div>
	<% end %>

    <%= will_paginate @users%>
		
</div>

app/views/users/search.html.erb
<% content_for :search do %>
	<%= stylesheet_link_tag "layout/main" %>
	<%= stylesheet_link_tag "container/search" %>
	<%= javascript_include_tag "controlElAttr" %>
	<%= javascript_include_tag "controlForm" %>
	<%= javascript_include_tag "util" %>
<% end %>
	
<div class="search-card-container mdl-grid">
	<div class="mdl-card mdl-shadow--4dp mdl-cell mdl-cell--6-col mdl-color--lime-50">
	    <div class="mdl-card__media mdl-color-text--grey-50 mdl-color--brown-500">
	        <h3>ユーザーを探す</h3>
	    </div>
	    
	    <div class="mdl-color-text--grey-700 mdl-card__supporting-text">

	        <%= form_for(@user, url: users_path, html: { method: :get }) do |f| %>
	    
        	<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        	    <%= f.label :area,'地域', { class:"mdl-textfield__label" } %><br />
        	    <%= f.text_field :area, { class:"mdl-textfield__input area-label" } %>
        	</div>
	        <%= render 'shared/area' %>
	      
        	<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        	    <%= f.label :kiryoku,'棋力', { class:"mdl-textfield__label" } %><br />
        	    <%= f.text_field :kiryoku, { class:"mdl-textfield__input kiryoku-label" } %>
        	</div>
	        <%= render 'shared/kiryoku' %>

        	<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        	    <%= f.label :age,'年齢', { class:"mdl-textfield__label" } %><br />
        	    <%= f.text_field :age, { class:"mdl-textfield__input age-label" } %>
        	</div>
	        <%= render 'shared/age' %>
	        
	        <div class="mdl-card__actions">
	            <%= f.submit "検索実行", class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect 
	            mdl-button--accent mdl-color--teal-300", id:"search_button" %>
	        </div>
	        
	        <input type="hidden" class="mdl-textfield__input" id="user_id" name="user[id]" value=<%=current_user.id%>>
	        
	        <% end %>
	    </div>
	</div>
</div>

app/views/users/show.html.erb
<% content_for :show do %>
	<%= stylesheet_link_tag "layout/main" %>
	<%= stylesheet_link_tag "container/show" %>
<% end %>
<div class="show-container">
	<div class="head">
	    <h3 class="head__name"><%= @user.name %></h3>
	    <div class="head__button">
	    	<% if current_user == @user %>
	    		<%= render 'shared/show/currentUserHead' %>
			<% else %>
				<%= render 'shared/show/otherUserHead' %>
	    	<% end %>
	    </div>
	</div>
	<div class="media-division">
	    <div class="media-division__image">
	        <% if @user.image_file_name.nil? %>
	            <%= image_tag "link/noImage.png", :size => "200x200" %>
	        <% else %>
	            <%= image_tag @user.image.url(:medium) %>
	        <% end %>
	    </div>
	    <div class="mdl-card mdl-shadow--4dp mdl-cell mdl-cell--12-col mdl-color--white">
	        <div class="mdl-card__title">
	            <p><%= @user.name %>さんの<br />フレンドリスト</p>
	        </div>
	        <div class="mdl-card__supporting-text">
	            <%= link_to "友達登録しているユーザ", following_user_path(@user), 
	            { :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect 
	            mdl-button--accent mdl-color--teal-300" } %>
	            <%= link_to "友達登録されているユーザ", followers_user_path(@user), 
	            { :class => "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect 
	            mdl-button--accent mdl-color--teal-300" } %>
	        </div>
	    </div>
	</div>
	<div class="table-division">
	    <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
	    	<tbody>
	        	<tr>
	        		<td class="mdl-data-table__cell--non-numeric">お名前</td>
	        		<td class="mdl-data-table__cell--non-numeric"><strong><%= @user.name %></strong></td>
	        	</tr>
	        	<tr>
	        		<td class="mdl-data-table__cell--non-numeric">性別</td>
	        		<% if @user.sex == 1 %>
	        			<td class="mdl-data-table__cell--non-numeric"><strong>男性</strong></td>
	        		<% else %>
	        			<td class="mdl-data-table__cell--non-numeric"><strong>女性</strong></td>
	        		<% end %>
	        	</tr>
	        	<tr>
	        		<td class="mdl-data-table__cell--non-numeric">生年月日</td>
	        		<td class="mdl-data-table__cell--non-numeric"><strong><%= @user.birthday %></strong></td>
	        	</tr>
	        	<tr>
	        		<td class="mdl-data-table__cell--non-numeric">メールアドレス</td>
	        		<% if @user.email_publish == 0 %>
	        			<td class="mdl-data-table__cell--non-numeric"><strong>非公開</strong></td>
	        		<% else %>
	        			<td class="mdl-data-table__cell--non-numeric"><strong><%= @user.email %></strong></td>
	        		<% end %>
	        	</tr>
	        </tbody>
	    </table>

	    <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
	        <tbody>
	        	<tr>
	        		<td class="mdl-data-table__cell--non-numeric">棋力</td>
	        		<% if @user.kiryoku.blank? %>
	        			<td class="mdl-data-table__cell--non-numeric"><strong>未設定</strong></td>
	        		<% else %>
	        			<td class="mdl-data-table__cell--non-numeric"><strong><%= @user.kiryoku %></strong></td>
	        		<% end %>
	        	</tr>
	        	<tr>
	        		<td class="mdl-data-table__cell--non-numeric">地域</td>
	          		<td class="mdl-data-table__cell--non-numeric"><strong><%= @user.area %></strong></td>
	        	</tr>
	        	<tr>
	        		<td class="mdl-data-table__cell--non-numeric">年齢</td>
	          		<td class="mdl-data-table__cell--non-numeric"><strong><%= @user.age %></strong></td>
	        	</tr>
	        	<tr>
	        		<td class="mdl-data-table__cell--non-numeric">ひとこと</td>
	        		<% if @user.kiryoku.blank? %>
	        			<td class="mdl-data-table__cell--non-numeric"><strong>未設定</strong></td>
	        		<% else %>
	        			<td class="mdl-data-table__cell--non-numeric"><strong><%= @user.comment %></strong></td>
	        		<% end %>
	        	</tr>
	    	</tbody>
	    </table>
	</div>
</div>

app/views/users/show_follow.html.erb
<% content_for :relation do %>
		<%= stylesheet_link_tag "layout/main" %>
		<%= stylesheet_link_tag "container/relation" %>
<% end %>

<div class="main-section-head mdl-typography--display-1">
		<div class="main-section-head__title">
				<i class="material-icons">content_copy</i><%= @title %>
		</div>
		<div class="main-section-head__button">    
        <% if current_page?(following_user_path(@user))%>
          	<div class="cards-section-button">  
              	<%= link_to "友達登録されているユーザを開く", followers_user_path(@user),
              	{ :class => "mdl-button mdl-js-button mdl-button--raised 
              	mdl-js-ripple-effect mdl-button--accent mdl-color--teal-300" }%>
          	</div>
        <% else %>
          	<div class="cards-section-button">  
              	<%= link_to "友達登録しているユーザを開く", following_user_path(@user),
              	{ :class => "mdl-button mdl-js-button mdl-button--raised 
              	mdl-js-ripple-effect mdl-button--accent mdl-color--teal-300" }%>
          	</div>
        <% end %>
		</div>
</div>

<div class="relation-card-container mdl-grid">
	<% if @users.count == 0 %>
		<h4>検索条件に一致するユーザーが見つかりませんでした</h4>
	<% end %>
	
	<% @users.each do |user| %>
		<div class="mdl-card mdl-shadow--4dp mdl-cell mdl-cell--3-col mdl-color--lime-50">
			<div class="mdl-card__media">
				<% if ! user.image_file_name.nil? %>
					<%= image_tag user.image.url , :size => "200x200" %>
				<% else %>
					<%= image_tag "link/noImage.png" , :size => "200x200" %>
				<% end %>
			</div>
			<div class="mdl-card__title">
				<h4 class="mdl-card__title-text"><%= user.name %></h4>
			</div>
			<div class="mdl-card__supporting-text">
				<span class="mdl-typography--font-light mdl-typography--subhead">
					<ul style="list-style:none">
						<li>性別: <% if user.sex == 1 %> 男性 <% else %> 女性 <% end %></li>
  		  		    	<li>棋力: <%= user.kiryoku %></li>
  		  		    	<li>地域: <%= user.area %></li>
  		  		    	<li>年齢: <%= user.age %></li>
  		  		    </ul>
  		  		</span>
  		  	</div>
			<div class="mdl-card__actions">
				<%= link_to user, { :class => "multiple-link mdl-button mdl-js-button mdl-typography--text-uppercase" }  do %>
					<span class="icon-link">プロフィールを開く
						<i class="material-icons">chevron_right</i>
					</span>
				<% end %>
			</div>
		</div>
	<% end %>

  <%= will_paginate @users%>
		
</div>