config/routes.rb
ShoYu::Application.routes.draw do
  
  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => "confirmations",
    omniauth_callbacks: 'omniauth_callbacks'
  }
  
  root to:"static_pages#home"
  
  resources :users, only: [:show, :index] do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :contacts, only: [:new, :create]
  match '/about', to: 'static_pages#about', via: 'get'
  match '/link', to: 'static_pages#link', via: 'get'
  match '/search', to: 'users#search' , via: 'get'
  match '/comfirm', to: 'static_pages#comfirm', via:'get'
  match '/sending', to: 'static_pages#sending', via:'get'
  match '/sending_contact', to: 'static_pages#sending_contact', via:'get'
  
  match '/message', to: 'messages#index' , via:'get'
  post 'post' => 'messages#post'
  post "messages/read_session"
  

end

app/views/layouts/_footer.html.erb
<footer class="mdl-mini-footer mdl-color--brown-500">
  <div class="mdl-mini-footer__left-section">
    <h4 class="mdl-logo">将友 SHO-YU</h4>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Simple header with scrollable tabs. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="sho-header mdl-layout__header mdl-color--brown-500">
        <!-- Title -->
        <div class="mdl-layout__header-row">
            <span class="mdl-layout-title"><strong>将棋のマッチングサイト&nbsp;&nbsp;&nbsp;将友</strong></span>
            <div class="sho-navigation-container">
                <nav class="sho-navigation mdl-navigation">
                    <%= link_to "OverView", root_path, { :class => "mdl-navigation__link mdl-typography--text-uppercase" } %>
                <% if signed_in? %>
                    <%= link_to "LogOut", destroy_user_session_path,{ method: :delete, class: "mdl-navigation__link mdl-typography--text-uppercase" } %>
                <% else %>
                    <%= link_to "Login", new_user_session_path, { :class => "mdl-navigation__link mdl-typography--text-uppercase" } %>
                <% end %>
                    <%= link_to "About", about_path, { :class => "mdl-navigation__link mdl-typography--text-uppercase" } %>
                    <%= link_to "Contact", new_contact_path, { :class => "mdl-navigation__link mdl-typography--text-uppercase" } %>
                    <%= link_to "Link", link_path, { :class => "mdl-navigation__link mdl-typography--text-uppercase" } %>
                </nav>
            </div>
        </div>
    </header>

    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Menu List</span>
    <main class="mdl-layout__content">
        <nav class="mdl-navigation">
            <%= link_to "OverView", root_path, { :class => "mdl-navigation__link" } %>
        	<% if signed_in? %>
        	  	<%= link_to "LogOut", destroy_user_session_path, { :class => "mdl-navigation__link" ,:method => "delete"} %>
        	  	<%= link_to "Profile", current_user, { :class => "mdl-navigation__link" } %>
                <%= link_to "Search User", search_path, { :class => "mdl-navigation__link" } %>
                <%= link_to "Friend List", following_user_path(current_user.id), { :class => "mdl-navigation__link" } %>
                <%= link_to "Messages", message_path, { :class => "mdl-navigation__link" } %>
            <% else %>
            	<%= link_to "LogIn", new_user_session_path, { :class => "mdl-navigation__link" } %>
        	<% end %> 
        </nav>
    </main>

    </div>
</div>

app/views/layouts/_main.html.erb
<div class="main-section">
    <%= yield %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoYu</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%=  yield :extend_menu %>
  <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.indigo-pink.min.css">
  <script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <%= csrf_meta_tags %>
  <%= yield :home %>
  <%= yield :singin %>
  <%= yield :signup %>
  <%= yield :about %>
  <%= yield :contact %>
  <%= yield :sending %>
  <%= yield :sending_contact %>
  <%= yield :confirm %>
  <%= yield :search %>
  <%= yield :edit %>
  <%= yield :index %>
  <%= yield :relation %>
  <%= yield :link %>
  <%= yield :show %>
  <%= yield :message %>
  <%= yield :message_info %>
  <%= yield :message_chat %>
</head>
<body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
  <!-- before script-->
  <script type="text/javascript">reload();</script>
  <%= render 'layouts/header' %>
  <%= render 'layouts/main' %>
  <%= render 'layouts/footer' %>
</body>
</html>